package org.geysermc.generator.mappings;

import com.google.common.hash.HashCode;
import com.mojang.logging.LogUtils;
import com.mojang.serialization.Codec;
import com.mojang.serialization.codecs.RecordCodecBuilder;
import it.unimi.dsi.fastutil.objects.Object2ObjectOpenHashMap;
import it.unimi.dsi.fastutil.objects.ObjectArrayList;
import net.minecraft.data.CachedOutput;
import org.apache.logging.log4j.core.pattern.AnsiEscape;
import org.geysermc.generator.MappingsGenerators;
import org.geysermc.generator.util.MappingsUtil;
import org.slf4j.Logger;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.CompletableFuture;

/// Used to keep a log of file hashes in VCS, without committing the actual files.
/// This is used to generate a "files changed report" at the end of the data generation process
public final class MappingsOutput implements CachedOutput, AutoCloseable {
    private static final Logger LOGGER = LogUtils.getLogger();

    private final MappingsAccess access;
    private final FileHashes hashes;
    private final CachedOutput delegate;

    private MappingsOutput(MappingsAccess access, FileHashes hashes, CachedOutput delegate) {
        this.access = access;
        this.hashes = hashes;
        this.delegate = delegate;
    }

    @Override
    public void writeIfNeeded(Path path, byte[] input, HashCode hash) throws IOException {
        hashes.write(access.mappingsFolder().relativize(path).toString(), hash);
        delegate.writeIfNeeded(path, input, hash);
    }

    @Override
    public void close() {
        hashes.sanitise();
        access.saveFile(delegate, FileType.FILE_HASHES, hashes).join();
        LOGGER.info(hashes.createReport());
        for (String removedFile : hashes.removed) {
            try {
                Files.delete(access.mappingsFolder().resolve(removedFile));
            } catch (IOException exception) {
                LOGGER.error("Failed to delete stale file {}!", removedFile, exception);
            }
        }
        LOGGER.info(MappingsGenerators.MOD_ID + " at your service. You're welcome :)");
    }

    public static CompletableFuture<MappingsOutput> open(MappingsAccess access, CachedOutput delegate) {
        return access.readFile(FileType.FILE_HASHES).exceptionally(throwable -> {
            LOGGER.warn("Failed to read existing file hashes, using empty map!", throwable);
            return new FileHashes(Map.of());
        }).thenApply(hashes -> new MappingsOutput(access, hashes, delegate));
    }

    public static final class FileHashes {
        public static final Codec<FileHashes> CODEC = RecordCodecBuilder.create(instance ->
                instance.group(
                        Codec.STRING.fieldOf("DO NOT EDIT THIS FILE").forGetter(_ -> "This file keeps hashes of generated output, used to report changed files. DO NOT EDIT."),
                        Codec.unboundedMap(Codec.STRING, Codec.INT).fieldOf("hashes").forGetter(hashes -> hashes.hashes)
                ).apply(instance, (_, hashes) -> new FileHashes(hashes))
        );

        private final Map<String, Integer> hashes = new Object2ObjectOpenHashMap<>();
        private final List<String> added = new ObjectArrayList<>();
        private final List<String> changed = new ObjectArrayList<>();
        private final List<String> unchanged = new ObjectArrayList<>();
        private final List<String> removed = new ObjectArrayList<>();

        private FileHashes(Map<String, Integer> hashes) {
            this.hashes.putAll(hashes);
        }

        private void write(String destination, HashCode hash) {
            Integer existingHash = hashes.get(destination);
            int newHash = hash.asInt();
            if (existingHash == null) {
                hashes.put(destination, newHash);
                added.add(destination);
            } else if (existingHash != newHash) {
                hashes.put(destination, newHash);
                changed.add(destination);
            } else {
                unchanged.add(destination);
            }
        }

        private void sanitise() {
            Set<String> destinations = Set.copyOf(hashes.keySet());
            for (String destination : destinations) {
                if (!added.contains(destination) && !changed.contains(destination) && !unchanged.contains(destination)) {
                    removed.add(destination);
                    hashes.remove(destination);
                }
            }
        }

        private boolean filesChanged() {
            return !added.isEmpty() || !changed.isEmpty() || !removed.isEmpty();
        }

        private String createReport() {
            if (!filesChanged()) {
                return "No files were changed since the last run";
            }

            StringBuilder report = new StringBuilder("Your changed files report:\n");

            addListToReport(report, added, "+", AnsiEscape.GREEN, "NEW");
            addListToReport(report, changed, "~", AnsiEscape.YELLOW, "CHANGED");
            addListToReport(report, removed, "-", AnsiEscape.RED, "DELETED");

            report.append("Please make sure to commit the \"file_hashes.json\" file to VCS, so that other developers can have a proper report, just like this one. Thank you.");

            return report.toString();
        }

        private void addListToReport(StringBuilder builder, List<String> files, String marker, AnsiEscape markerColor, String modifier) {
            if (!files.isEmpty()) {
                builder.append(MappingsUtil.formatString("--- " + modifier + " FILES ---", AnsiEscape.BOLD)).append("\n");

                for (String file : files) {
                    builder.append(MappingsUtil.formatString("[" + marker + "] ", markerColor, AnsiEscape.BOLD)).append(file).append("\n");
                }
            }
        }
    }
}
