name: Publish Release

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Gradle
        uses: GeyserMC/actions/setup-gradle-composite@master
        with:
          setup-java_java-version: 25

      # Also runs the generator, and writes a bunch of info to GITHUB_OUTPUT
      - name: Generate Mappings and Prepare Release
        id: prepare-release
        run: ./gradlew prepareRelease

      - name: Publish Release to GitHub
        uses: eclipseisoffline/geyser-actions/release@master
        with:
          appID: ${{ secrets.RELEASE_APP_ID }}
          appPrivateKey: ${{ secrets.RELEASE_APP_PK }}
          files: |
            ${{ steps.prepare-release.outputs.full_file }}
            ${{ steps.prepare-release.outputs.min_file }}
          discordWebhook: ${{ secrets.DISCORD_WEBHOOK }}
          # releaseBody: "" TODO
          releaseName: Mappings v${{ steps.prepare-release.outputs.version }}
          tag: ${{ steps.prepare-release.outputs.version }} # TODO build number
          additionalTags: ${{ steps.prepare-release.outputs.java_version }}_${{ steps.prepare-release.outputs.bedrock_version }}
